version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6969:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - ./s3-data:/data/minio
    ports:
      - "9003:9000"
      - "9099:9090"
    command: minio server /data/minio --console-address ":9090"
  minio-mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 root password;
        mc mb --quiet minio/wigglepaw;
        mc anonymous set download minio/wigglepaw;
        mc admin user svcacct add --access-key J9jiu0i7jrqoJEwO --secret-key 29oOdS0Buo99jA4KXeKwLfbK1cTbIDpm minio root
      "
