version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6969:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
